default:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    before_script:
        - docker info

build:
    stage: build
    parallel:
        matrix:
            - COMPONENT: [api, worker]
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Default branch leaves tag empty (= latest tag)
    # All other branches are tagged with the escaped branch name (commit ref slug)
    script:
         - cd "$CI_PROJECT_DIR/src/$COMPONENT"
         - docker build .