#from refueling import Refueling
from datetime import datetime
import logging
import json
import time
import requests

logging.basicConfig(level=logging.DEBUG)
    
class vereinsflieger(object):
    accesstoken=""
    url=""

    def __init__(self, url):
        self.url = url

    def get_accesstoken(self):
        response = requests.get("https://" + self.url + "/interface/rest/auth/accesstoken").json()
        logging.debug("Get accesstoken: %s", response)
        self.accesstoken=response["accesstoken"]

    def signin(self, user, pwd, appkey):

        # get access token
        self.get_accesstoken()

        payload={}
        headers = {}
        url = "https://www.vereinsflieger.de/interface/rest/auth/signin?" + \
            "accesstoken=" + self.accesstoken + \
            "&username=" + user + \
            "&password=" + pwd + \
            "&appkey=" + appkey
        response = requests.request("POST", url, headers=headers, data=payload)
        #respone=requests.post("https://" + self.url + "/interface/rest/auth/singin", params=params, headers=headers, data=payload)
        logging.debug("Respone: %s", response.json())

    def signout(self):
        payload={}
        headers = {}

        url = "https://www.vereinsflieger.de/interface/rest/auth/signout?" + \
            "accesstoken=" + self.accesstoken
        response = requests.request("DELETE", url, headers=headers, data=payload)
        #respone=requests.post("https://" + self.url + "/interface/rest/auth/singin", params=params, headers=headers, data=payload)
        logging.debug("Respone: %s", response)

    def add_sale(self, rf):
        logging.info('Enter Add Sale: %s', rf)
        payload={}
        headers = {}
        params = {
            'accesstoken': self.accesstoken,
            'bookingdate': rf["date"],
            'articleid': rf["article"],
            'memberid': rf["memberid"],
            'amount': rf["amount"],
            'callsign': rf["aircraft"],
            'comment' : 'Generated by GA Fuel Station'
             }
        
        logging.info('Add Sale: %s', params)
        response=requests.post("https://" + self.url + "/interface/rest/sale/add", params=params, headers=headers, data=payload).json()
        logging.debug("Respone: %s", response)
 
        if response['httpstatuscode'] is 200:
            logging.info("Sale successfully added !")
        else:
            logging.error("Add Sale FAILED!\n VF Response: %s", response)

    def get_members(self):
        payload={}
        headers = {}
        params = {
            'accesstoken': self.accesstoken,
             }
        
        logging.info('Get members')
        response=requests.post("https://" + self.url + "/interface/rest/user/list", params=params, headers=headers, data=payload).json()
        logging.info("Respone: %s", response)
        
        #if response['httpstatuscode'] is '200':
        #    logging.info("Sale successfully added !")
        #else:
        #    logging.error("Add Sale FAILED!\n VF Response: %s", response)
    
    def get_properties_from_id(self, id):
        payload={}
        headers = {}
        params = {
            'accesstoken': self.accesstoken,
             }
        
        logging.info('Get properties from ID')
        response=requests.post("https://" + self.url + "/interface/rest/user/list", params=params, headers=headers, data=payload)
        
        logging.debug("Respone: %s", response)
        
        data = response.json()
        props = {}
        for key in data.keys():
            try: 
                if data[key]['memberid'] == str(id):
                    logging.debug("Member match!")
                    member_record = data[key]
                    for key, value in member_record.items():
                        if key.startswith('prop'):
                            props[value['name']]=value['value']

                    break
            except:
                logging.info("Member not found!")
                return None
        logging.debug("Properties: %s", props)
        return props
        
 

