#from refueling import Refueling
from datetime import datetime
import logging
import json
import time
import requests



import paho.mqtt.client as mqtt

client = mqtt.Client()

logging.basicConfig(level=logging.DEBUG)
    
class vereinsflieger(object):
    accesstoken=""
    url=""

    def __init__(self, url):
        self.url = url

    def get_accesstoken(self):
        response = requests.get("https://" + self.url + "/interface/rest/auth/accesstoken").json()
        logging.debug("Get accesstoken: %s", response)
        self.accesstoken=response["accesstoken"]

    def signin(self, user, pwd, appkey):

        # get access token
        self.get_accesstoken()

        payload={}
        headers = {}
        url = "https://www.vereinsflieger.de/interface/rest/auth/signin?" + \
            "accesstoken=" + self.accesstoken + \
            "&username=" + user + \
            "&password=" + pwd + \
            "&appkey=" + appkey
        response = requests.request("POST", url, headers=headers, data=payload)
        #respone=requests.post("https://" + self.url + "/interface/rest/auth/singin", params=params, headers=headers, data=payload)
        logging.debug("Respone: %s", response.json())

    def signout(self):
        payload={}
        headers = {}

        url = "https://www.vereinsflieger.de/interface/rest/auth/signout?" + \
            "accesstoken=" + self.accesstoken
        response = requests.request("DELETE", url, headers=headers, data=payload)
        #respone=requests.post("https://" + self.url + "/interface/rest/auth/singin", params=params, headers=headers, data=payload)
        logging.debug("Respone: %s", response.json())

    def add_sale(self, rf):
        logging.info('Enter Add Sale: %s', rf)
        payload={}
        headers = {}
        params = {
            'accesstoken': self.accesstoken,
            'bookingdate': datetime.today().strftime('%Y-%m-%d'),
            'articleid': rf["article"],
            'memberid': rf["memberid"],
            'amount': rf["amount"],
            'callsign': rf["aircraft"],
            'comment' : 'Generated by GA Fuel Station'
             }
        
        logging.info('Add Sale: %s', params)
        response=requests.post("https://" + self.url + "/interface/rest/sale/add", params=params, headers=headers, data=payload).json()
        logging.debug("Respone: %s", response)
 
        if response['httpstatuscode'] is 200:
            logging.info("Sale successfully added !")
        else:
            logging.error("Add Sale FAILED!\n VF Response: %s", response)

    def get_members(self):
        payload={}
        headers = {}
        params = {
            'accesstoken': self.accesstoken,
             }
        
        logging.info('Add Sale: %s', params)
        response=requests.post("https://" + self.url + "/interface/rest/user/list", params=params, headers=headers, data=payload).json()
        logging.debug("Respone: %s", response)
        
        #if response['httpstatuscode'] is '200':
        #    logging.info("Sale successfully added !")
        #else:
        #    logging.error("Add Sale FAILED!\n VF Response: %s", response)
    

    
    
                


if __name__ == '__main__':
    # Read configuration
    with open("config.json", "r") as jsonfile:
        config = json.load(jsonfile)
    logging.info("Configuration Read successful: %s", config)

    #Setup MQTT
    client.on_connect = on_connect
    client.on_message = push_to_vf
    client.on_disconnect = on_disconnect

    # connect to database
    logging.info("Connecting to database ...")
    

   
        
 

